global:
  cloudOrigin: "azure" # possible valulues: azure, aws, gcp, alibaba, digitalocean, oci, openstack, ibmcloud

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/privileged-containers/
privilegedContainer:
  enabled: true
  excludedNamespaces: ["kube-system", "default"]
  exemptImages: []

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/host-namespaces/
hostNamespace:
  enabled: true
  excludedNamespaces: []

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/allow-privilege-escalation
privilegeEscalationContainer:
  enabled: true
  exemptImages: []

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/host-filesystem
hostFilesystem:
  enabled: true
  allowedHostPaths: []
    # - readOnly: true
    #   pathPrefix: "/tmp"

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/read-only-root-filesystem
readOnlyRootFilesystem:
  enabled: true
  exemptImages: []

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/allowedrepos
allowedRepositories:
  enabled: true
  repos: ["registry.k8s.io/", "nginx"]

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/automount-serviceaccount-token
automountServiceAccountTokenForPod:
  enabled: true
  excludedNamespaces: ["kube-system"]

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/block-endpoint-edit-default-role
BlockEndpointEditDefaultRole:
  enabled: true

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/block-nodeport-services
BlockNodePort:
  enabled: true

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/block-wildcard-ingress
BlockWildcardIngress:
  enabled: true

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/containerresources
RequiredResources:
  enabled: true
  limits: ["cpu","memory"]
  requests: ["cpu","memory"]

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/disallowanonymous
DisallowAnonymousAccess:
  enabled: true
  allowedRoles: ["cluster-role-1"]

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/disallowedtags
DisallowTags:
  enabled: true
  tags: ["latest"]
  exemptImages: []

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/ephemeralstoragelimit
ContainerEphemeralStorageLimit:
  enabled: true
  ephemeralStorage: "500Mi"
  exemptImages: []

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/externalip
ExternalIps:
  enabled: true
  allowedIPs: []

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/replicalimits
ReplicaLimits:
  enabled: true
  ranges:
    - min_replicas: 2
      max_replicas: 50

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/storageclass
StorageClass:
  enabled: true
  includeStorageClassesInMessage: true
  allowedStorageClasses: []

SvcLoadbalancerAnnotations:
  enabled: true

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/fsgroup
fsGroup:
  enabled: false
  rule : ["MayRunAs"]
  ranges: 
   - min: 1
     max: 1000

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/capabilities
capabilities:
  enabled: false
  includeNamespaces: ["default"]
  allowedCapabilities: []
  requiredDropCapabilities: []

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/disallowedrepos
DisallowedRepositories:
  enabled: false
  repos: ["k8s.gcr.io/"]

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/horizontalpodautoscaler
HorizontalPodAutoscaler:
  enabled: false
  minimumReplicaSpread: 1
  enforceScaleTargetRef: true
  ranges:
    - min_replicas: 3
      max_replicas: 6

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/httpsonly
IngressHttpsOnly:
  enabled: false
  tlsOptional: true

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/imagedigests
ImageDigests:
  enabled: false
  namespaces: ["default"]

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/poddisruptionbudget
PodDisruptionBudget:
  enabled: false
  kinds:
    - apiGroups: ["apps"]
      kinds: ["Deployment", "StatefulSet"]
    - apiGroups: ["policy"]
      kinds: ["PodDisruptionBudget"]
    - apiGroups: [""]
      kinds: ["ReplicationController"]

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/requiredannotations
RequiredAnnotations:
  enabled: false
  message: "All services must have a `a8r.io/owner` and `a8r.io/runbook` annotations."
  annotations:
    - key: a8r.io/owner
      # Matches email address or github user
      allowedRegex: ^([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}|[a-z]{1,39})$
    - key: a8r.io/runbook
      # Matches urls including or not http/https
      allowedRegex: ^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/requiredprobes
RequiredProbes:
  enabled: false
  probes: ["readinessProbe", "livenessProbe"]
  probeTypes: ["tcpSocket", "httpGet", "exec"]

# https://open-policy-agent.github.io/gatekeeper-library/website/validation/requiredlabels
RequiredLabels:
  enabled: false
  message: "All namespaces must have an `owner` label that points to your company username"
  labels:
    - key: owner
      allowedRegex: "^[a-zA-Z]+.agilebank.demo$"