{{- if .Values.DisallowRoot.enabled -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sValidateRunAsNonRoot
metadata:
  name: disallow-container-as-root
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    exemptImages: 
      {{ .Values.DisallowRoot.exemptImages | toYaml | nindent 6 }}
{{- end -}}