{{ if .Values.privilegedContainer.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPPrivilegedContainer
metadata:
  name: psp-privileged-container
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: 
      {{ .Values.privilegedContainer.excludedNamespaces | toYaml | nindent 6 }}
  parameters:
    exemptImages: 
      {{ .Values.privilegedContainer.exemptImages | toYaml | nindent 6 }}
{{- end -}}