{{- if .Values.privilegeEscalationContainer.enabled -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowPrivilegeEscalationContainer
metadata:
  name: psp-allow-privilege-escalation-container
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    exemptImages: 
      {{ .Values.privilegeEscalationContainer.exemptImages | toYaml | nindent 6 }}
{{- end -}}