{{- if .Values.RequiredResources.enabled -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredResources
metadata:
  name: container-must-have-limits-and-requests
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    limits:
      {{ .Values.RequiredResources.limits | toYaml | nindent 6 }}
    requests:
      {{ .Values.RequiredResources.requests | toYaml | nindent 6 }}
{{- end -}}
