{{- if .Values.RequiredLabels.enabled -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: all-must-have-owner
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    message: {{ .Values.RequiredLabels.message }}
    labels:
      {{ .Values.RequiredLabels.labels | toYaml | nindent 6 }}
{{- end -}}
