{{- if .Values.StorageClass.enabled -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sStorageClass
metadata:
  name: allowed-storageclass
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["PersistentVolumeClaim"]
      - apiGroups: ["apps"]
        kinds: ["StatefulSet"]
  parameters:
    includeStorageClassesInMessage: {{ .Values.StorageClass.includeStorageClassesInMessage }}
    allowedStorageClasses:
      {{ .Values.StorageClass.allowedStorageClasses | toYaml | nindent 6 }}
{{- end -}}
